### ISSUE TITLE
url->path is different on the blog compared to in the repo

### ISSUE THREAD

**Issue by peter-wilkins** [codonnell/mygiftlist-blog#1]
great job with the blog - it's really helped me get started with fulcro. thanks!

url->path is different on the blog compared to in the repo:

```
(let [path (-> url (str/split "?") first (str/split "/") rest vec)]
    (if (seq path) path ["home"]))
```

https://github.com/codonnell/mygiftlist-blog/blob/master/src/rocks/mygiftlist/client.cljs#L23

as there is already logic to redirect to home in the `history` form then perhaps the version in git is fine (but with an updated doc string)

perhaps pulling out the string would be more readable:

 ```
(def default-route ["home"])
```

```
(defonce history (pushy/pushy
                   (fn [path]
                     (dr/change-route SPA path))
                   (fn [url]
                     (let [path (url->path url)]
                       (if (routable-path? SPA path)
                         path
                         default-route)))))
```

**Comment by codonnell** [comment]
Thanks for pointing this out, and I'm glad my blog posts have been helpful! I've been trying really hard to keep the two in sync, but I'm bound to make some mistakes. I'll fix this up.

**Comment by codonnell** [comment]
I like your suggestion of using `default-route`, so I've adopted that. The blog post and git repo should match now. Thanks again for taking the time to point this out!
