### ISSUE TITLE
case for user by id not found

### ISSUE THREAD

**Issue by laconiccrafts** [codonnell/mygiftlist-blog#2]
I'm currently learning pathom and stumbled upon your blog (very nice!).

I find that when I ask pathom for a user that does not exist in the db, and therefore my query returns nil, the parser will still return a map, i.e:

```
(parser {} {[:user/id 25] [:user/id :user/username]})
; => {:user/id 25}
```
Is there a plugin to deal with that? So far I've search in vain for an answer.

Thanks!

**Comment by codonnell** [comment]
Hi, I'm glad you've found my blog useful! If you created your parser as I have in this repo, I believe that behavior comes from the inclusion of `p/map-reader`. By using the ident `[:user/id 25]` in your query, you're asserting that the current entity has the attribute `:user/id` with the value `25`. There's more info about how that works [in the docs](https://wilkerlucio.github.io/pathom/#_the_map_reader). The section on the map reader as well as the entities stuff should help you understand what's going on.

If you don't want that behavior, I believe removing `p/map-reader` from your parser should do what you've requested. That said, I don't think it's a good idea to do so. It would be nice to better understand why you're finding the behavior problematic.

I would highly recommend asking these kinds of questions in the #pathom channel in the [Clojurians slack](https://clojurians.net). There are lots of helpful people who know pathom much better than I.

**Comment by laconiccrafts** [comment]
I'll check it out.

I use re-frame instead of fulcro (I never used fulcro), so that may be the reason I don't understand this functionality. Does fulcro has a use for that map, instead of nil? Just curious.

Thank you!
